export type ThaiProvince = {
  id: string;
  name: string;
  region: "เหนือ" | "อีสาน" | "กลาง" | "ตะวันออก" | "ตะวันตก" | "ใต้";
};

export const THAI_PROVINCES: ThaiProvince[] = [
  { id: "bangkok", name: "กรุงเทพมหานคร", region: "กลาง" },
  { id: "krabi", name: "กระบี่", region: "ใต้" },
  { id: "kanchanaburi", name: "กาญจนบุรี", region: "ตะวันตก" },
  { id: "kalasin", name: "กาฬสินธุ์", region: "อีสาน" },
  { id: "kamphaeng-phet", name: "กำแพงเพชร", region: "กลาง" },
  { id: "khon-kaen", name: "ขอนแก่น", region: "อีสาน" },
  { id: "chanthaburi", name: "จันทบุรี", region: "ตะวันออก" },
  { id: "chachoengsao", name: "ฉะเชิงเทรา", region: "ตะวันออก" },
  { id: "chonburi", name: "ชลบุรี", region: "ตะวันออก" },
  { id: "chainat", name: "ชัยนาท", region: "กลาง" },
  { id: "ชัยภูมิ", name: "ชัยภูมิ", region: "อีสาน" },
  { id: "chumphon", name: "ชุมพร", region: "ใต้" },
  { id: "chiang-rai", name: "เชียงราย", region: "เหนือ" },
  { id: "chiang-mai", name: "เชียงใหม่", region: "เหนือ" },
  { id: "trang", name: "ตรัง", region: "ใต้" },
  { id: "trat", name: "ตราด", region: "ตะวันออก" },
  { id: "tak", name: "ตาก", region: "ตะวันตก" },
  { id: "nakhon-nayok", name: "นครนายก", region: "กลาง" },
  { id: "nakhon-pathom", name: "นครปฐม", region: "กลาง" },
  { id: "nakhon-phanom", name: "นครพนม", region: "อีสาน" },
  { id: "nakhon-ratchasima", name: "นครราชสีมา", region: "อีสาน" },
  { id: "nakhon-si-thammarat", name: "นครศรีธรรมราช", region: "ใต้" },
  { id: "nakhon-sawan", name: "นครสวรรค์", region: "กลาง" },
  { id: "nonthaburi", name: "นนทบุรี", region: "กลาง" },
  { id: "narathiwat", name: "นราธิวาส", region: "ใต้" },
  { id: "nan", name: "น่าน", region: "เหนือ" },
  { id: "bueng-kan", name: "บึงกาฬ", region: "อีสาน" },
  { id: "buri-ram", name: "บุรีรัมย์", region: "อีสาน" },
  { id: "pathum-thani", name: "ปทุมธานี", region: "กลาง" },
  { id: "prachuap-khiri-khan", name: "ประจวบคีรีขันธ์", region: "ตะวันตก" },
  { id: "prachin-buri", name: "ปราจีนบุรี", region: "ตะวันออก" },
  { id: "pattani", name: "ปัตตานี", region: "ใต้" },
  { id: "phra-nakhon-si-ayutthaya", name: "พระนครศรีอยุธยา", region: "กลาง" },
  { id: "phang-nga", name: "พังงา", region: "ใต้" },
  { id: "phatthalung", name: "พัทลุง", region: "ใต้" },
  { id: "phichit", name: "พิจิตร", region: "กลาง" },
  { id: "phitsanulok", name: "พิษณุโลก", region: "เหนือ" },
  { id: "phetchaburi", name: "เพชรบุรี", region: "ตะวันตก" },
  { id: "phetchabun", name: "เพชรบูรณ์", region: "เหนือ" },
  { id: "phrae", name: "แพร่", region: "เหนือ" },
  { id: "phayao", name: "พะเยา", region: "เหนือ" },
  { id: "phuket", name: "ภูเก็ต", region: "ใต้" },
  { id: "maha-sarakham", name: "มหาสารคาม", region: "อีสาน" },
  { id: "mukdahan", name: "มุกดาหาร", region: "อีสาน" },
  { id: "mae-hong-son", name: "แม่ฮ่องสอน", region: "เหนือ" },
  { id: "yasothon", name: "ยโสธร", region: "อีสาน" },
  { id: "yala", name: "ยะลา", region: "ใต้" },
  { id: "roi-et", name: "ร้อยเอ็ด", region: "อีสาน" },
  { id: "ranong", name: "ระนอง", region: "ใต้" },
  { id: "rayong", name: "ระยอง", region: "ตะวันออก" },
  { id: "ratchaburi", name: "ราชบุรี", region: "ตะวันตก" },
  { id: "lopburi", name: "ลพบุรี", region: "กลาง" },
  { id: "lamphun", name: "ลำพูน", region: "เหนือ" },
  { id: "lampang", name: "ลำปาง", region: "เหนือ" },
  { id: "loei", name: "เลย", region: "อีสาน" },
  { id: "si-sa-ket", name: "ศรีสะเกษ", region: "อีสาน" },
  { id: "sakon-nakhon", name: "สกลนคร", region: "อีสาน" },
  { id: "songkhla", name: "สงขลา", region: "ใต้" },
  { id: "samut-sakhon", name: "สมุทรสาคร", region: "กลาง" },
  { id: "samut-prakan", name: "สมุทรปราการ", region: "กลาง" },
  { id: "samut-songkhram", name: "สมุทรสงคราม", region: "กลาง" },
  { id: "saraburi", name: "สระบุรี", region: "กลาง" },
  { id: "sa-kaeo", name: "สระแก้ว", region: "ตะวันออก" },
  { id: "sing-buri", name: "สิงห์บุรี", region: "กลาง" },
  { id: "sukhothai", name: "สุโขทัย", region: "เหนือ" },
  { id: "suphan-buri", name: "สุพรรณบุรี", region: "กลาง" },
  { id: "surat-thani", name: "สุราษฎร์ธานี", region: "ใต้" },
  { id: "surin", name: "สุรินทร์", region: "อีสาน" },
  { id: "satun", name: "สตูล", region: "ใต้" },
  { id: "nong-khai", name: "หนองคาย", region: "อีสาน" },
  { id: "nong-bua-lamphu", name: "หนองบัวลำภู", region: "อีสาน" },
  { id: "amnat-charoen", name: "อำนาจเจริญ", region: "อีสาน" },
  { id: "udon-thani", name: "อุดรธานี", region: "อีสาน" },
  { id: "uttaradit", name: "อุตรดิตถ์", region: "เหนือ" },
  { id: "uthai-thani", name: "อุทัยธานี", region: "กลาง" },
  { id: "ubon-ratchathani", name: "อุบลราชธานี", region: "อีสาน" },
  { id: "ang-thong", name: "อ่างทอง", region: "กลาง" }
];

export function getRandomThaiProvince(excludeId?: string) {
  const pool = THAI_PROVINCES.filter((province) => province.id !== excludeId);
  return pool[Math.floor(Math.random() * pool.length)] || THAI_PROVINCES[0];
}
